services:
  - type: web
    name: fullstackjs-app
    env: node
    plan: free
    buildCommand: |
      # Install + build client
      npm ci --prefix client --include=dev
      npm run build --prefix client
      echo "== Listing client/dist =="
      ls -la client/dist || true
      # Copy build to server/public so Express can serve it at runtime
      rm -rf server/public
      mkdir -p server/public
      cp -r client/dist/* server/public/
      echo "== Listing server/public after copy =="
      ls -la server/public || true
      # Install server deps
      npm ci --prefix server
    startCommand: node server/user.js
    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: fullstackjs
      - key: JWT_SECRET
        sync: false
